import type { ThemeTokens } from '../types/theme';

export const DEFAULT_TOKENS: ThemeTokens = {
  light: {
    colors: {
      '--color-primary': '#4F46E5',
      '--color-primary-light': '#818CF8',
      '--color-secondary': '#EC4899',
      '--color-surface': '#FFFFFF',
      '--color-background': '#F9FAFB',
      '--color-text-primary': '#111827',
      '--color-text-secondary': '#6B7280',
      '--color-text-accent': '#4F46E5',
      '--color-border': '#E5E7EB',
      '--color-error': '#EF4444',
      '--color-success': '#10B981',
      '--color-warning': '#F59E0B',
    },
    typography: {
      '--font-family-base': '"Inter", sans-serif',
      '--font-family-heading': '"Inter", sans-serif',
      '--font-size-xs': '0.75rem',
      '--font-size-sm': '0.875rem',
      '--font-size-base': '1rem',
      '--font-size-lg': '1.125rem',
      '--font-size-xl': '1.25rem',
      '--font-size-2xl': '1.5rem',
      '--font-weight-normal': '400',
      '--font-weight-medium': '500',
      '--font-weight-bold': '700',
      '--line-height-tight': '1.25',
      '--line-height-normal': '1.5',
      '--line-height-relaxed': '1.75',
    },
    shapes: {
      '--radius-sm': '4px',
      '--radius-md': '8px',
      '--radius-lg': '16px',
      '--radius-full': '9999px',
      '--shadow-sm': '0 1px 2px rgba(0,0,0,0.05)',
      '--shadow-md': '0 4px 6px rgba(0,0,0,0.07)',
      '--shadow-lg': '0 10px 15px rgba(0,0,0,0.1)',
      '--shape-opacity': '1',
    },
    spacing: {
      '--spacing-xs': '4px',
      '--spacing-sm': '8px',
      '--spacing-md': '16px',
      '--spacing-lg': '24px',
      '--spacing-xl': '32px',
      '--spacing-2xl': '48px',
    },
  },
  dark: {
    colors: {
      '--color-primary': '#818CF8',
      '--color-primary-light': '#A5B4FC',
      '--color-secondary': '#F472B6',
      '--color-surface': '#1F2937',
      '--color-background': '#111827',
      '--color-text-primary': '#F9FAFB',
      '--color-text-secondary': '#9CA3AF',
      '--color-text-accent': '#818CF8',
      '--color-border': '#374151',
      '--color-error': '#FCA5A5',
      '--color-success': '#6EE7B7',
      '--color-warning': '#FCD34D',
    },
    typography: {
      '--font-family-base': '"Inter", sans-serif',
      '--font-family-heading': '"Inter", sans-serif',
      '--font-size-xs': '0.75rem',
      '--font-size-sm': '0.875rem',
      '--font-size-base': '1rem',
      '--font-size-lg': '1.125rem',
      '--font-size-xl': '1.25rem',
      '--font-size-2xl': '1.5rem',
      '--font-weight-normal': '400',
      '--font-weight-medium': '500',
      '--font-weight-bold': '700',
      '--line-height-tight': '1.25',
      '--line-height-normal': '1.5',
      '--line-height-relaxed': '1.75',
    },
    shapes: {
      '--radius-sm': '4px',
      '--radius-md': '8px',
      '--radius-lg': '16px',
      '--radius-full': '9999px',
      '--shadow-sm': '0 1px 2px rgba(0,0,0,0.05)',
      '--shadow-md': '0 4px 6px rgba(0,0,0,0.07)',
      '--shadow-lg': '0 10px 15px rgba(0,0,0,0.1)',
      '--shape-opacity': '1',
    },
    spacing: {
      '--spacing-xs': '4px',
      '--spacing-sm': '8px',
      '--spacing-md': '16px',
      '--spacing-lg': '24px',
      '--spacing-xl': '32px',
      '--spacing-2xl': '48px',
    },
  },
};
